//
// Generated file, do not edit! Created by opp_msgtool 6.2 from DroneAuthMessages.msg.
//

#ifndef __DRONEAUTHMESSAGES_M_H
#define __DRONEAUTHMESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class AuthCommit;
class AuthChallenge;
class AuthResponse;
class AuthResult;
class HeartbeatMessage;
class StateSyncMessage;
class GCSAnnouncementMessage;
class GCSSwitchAckMessage;
class FailoverCompleteMessage;
// cplusplus {{
#include <string>
// }}

/**
 * Class generated from <tt>DroneAuthMessages.msg:9</tt> by opp_msgtool.
 * <pre>
 * // Commitment Phase: Drone sends t = g^r mod p
 * packet AuthCommit
 * {
 *     int droneId;
 *     string commitment;  // t value as string
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class AuthCommit : public ::omnetpp::cPacket
{
  protected:
    int droneId = 0;
    omnetpp::opp_string commitment;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const AuthCommit& other);

  protected:
    bool operator==(const AuthCommit&) = delete;

  public:
    AuthCommit(const char *name=nullptr, short kind=0);
    AuthCommit(const AuthCommit& other);
    virtual ~AuthCommit();
    AuthCommit& operator=(const AuthCommit& other);
    virtual AuthCommit *dup() const override {return new AuthCommit(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDroneId() const;
    virtual void setDroneId(int droneId);

    virtual const char * getCommitment() const;
    virtual void setCommitment(const char * commitment);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AuthCommit& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AuthCommit& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>DroneAuthMessages.msg:16</tt> by opp_msgtool.
 * <pre>
 * // Challenge Phase: GCS sends random challenge
 * packet AuthChallenge
 * {
 *     int droneId;
 *     string challenge;  // c value as string
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class AuthChallenge : public ::omnetpp::cPacket
{
  protected:
    int droneId = 0;
    omnetpp::opp_string challenge;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const AuthChallenge& other);

  protected:
    bool operator==(const AuthChallenge&) = delete;

  public:
    AuthChallenge(const char *name=nullptr, short kind=0);
    AuthChallenge(const AuthChallenge& other);
    virtual ~AuthChallenge();
    AuthChallenge& operator=(const AuthChallenge& other);
    virtual AuthChallenge *dup() const override {return new AuthChallenge(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDroneId() const;
    virtual void setDroneId(int droneId);

    virtual const char * getChallenge() const;
    virtual void setChallenge(const char * challenge);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AuthChallenge& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AuthChallenge& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>DroneAuthMessages.msg:23</tt> by opp_msgtool.
 * <pre>
 * // Response Phase: Drone sends s = r + c*x mod (p-1)
 * packet AuthResponse
 * {
 *     int droneId;
 *     string response;  // s value as string
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class AuthResponse : public ::omnetpp::cPacket
{
  protected:
    int droneId = 0;
    omnetpp::opp_string response;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const AuthResponse& other);

  protected:
    bool operator==(const AuthResponse&) = delete;

  public:
    AuthResponse(const char *name=nullptr, short kind=0);
    AuthResponse(const AuthResponse& other);
    virtual ~AuthResponse();
    AuthResponse& operator=(const AuthResponse& other);
    virtual AuthResponse *dup() const override {return new AuthResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDroneId() const;
    virtual void setDroneId(int droneId);

    virtual const char * getResponse() const;
    virtual void setResponse(const char * response);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AuthResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AuthResponse& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>DroneAuthMessages.msg:30</tt> by opp_msgtool.
 * <pre>
 * // Verification Result
 * packet AuthResult
 * {
 *     int droneId;
 *     bool authenticated;
 *     string reason;
 *     simtime_t timestamp;
 * }
 * // ============================================================================
 * // PHASE 2: Dual GCS Messages
 * // ============================================================================
 * </pre>
 */
class AuthResult : public ::omnetpp::cPacket
{
  protected:
    int droneId = 0;
    bool authenticated = false;
    omnetpp::opp_string reason;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const AuthResult& other);

  protected:
    bool operator==(const AuthResult&) = delete;

  public:
    AuthResult(const char *name=nullptr, short kind=0);
    AuthResult(const AuthResult& other);
    virtual ~AuthResult();
    AuthResult& operator=(const AuthResult& other);
    virtual AuthResult *dup() const override {return new AuthResult(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDroneId() const;
    virtual void setDroneId(int droneId);

    virtual bool getAuthenticated() const;
    virtual void setAuthenticated(bool authenticated);

    virtual const char * getReason() const;
    virtual void setReason(const char * reason);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AuthResult& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AuthResult& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>DroneAuthMessages.msg:41</tt> by opp_msgtool.
 * <pre>
 * // Heartbeat message between GCS nodes
 * packet HeartbeatMessage
 * {
 *     string senderGCS;           // "PrimaryGCS" or "BackupGCS"
 *     simtime_t timestamp;        // When heartbeat was sent
 *     string status = "alive";    // "alive", "shutting_down", "overloaded"
 *     int activeDrones;           // Number of authenticated drones
 * }
 * </pre>
 */
class HeartbeatMessage : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string senderGCS;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    omnetpp::opp_string status = "alive";
    int activeDrones = 0;

  private:
    void copy(const HeartbeatMessage& other);

  protected:
    bool operator==(const HeartbeatMessage&) = delete;

  public:
    HeartbeatMessage(const char *name=nullptr, short kind=0);
    HeartbeatMessage(const HeartbeatMessage& other);
    virtual ~HeartbeatMessage();
    HeartbeatMessage& operator=(const HeartbeatMessage& other);
    virtual HeartbeatMessage *dup() const override {return new HeartbeatMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSenderGCS() const;
    virtual void setSenderGCS(const char * senderGCS);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);

    virtual const char * getStatus() const;
    virtual void setStatus(const char * status);

    virtual int getActiveDrones() const;
    virtual void setActiveDrones(int activeDrones);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HeartbeatMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HeartbeatMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>DroneAuthMessages.msg:49</tt> by opp_msgtool.
 * <pre>
 * // State synchronization message
 * packet StateSyncMessage
 * {
 *     int droneId;                    // Which drone's state
 *     bool authenticated;             // Authentication status
 *     string commitment;              // Last commitment value
 *     long publicKey;                 // Drone public key
 *     simtime_t lastAuthTime;         // Last authentication timestamp
 *     int authCount;                  // Total authentications
 *     bool fullSync = false;          // Is this a full state sync?
 * }
 * </pre>
 */
class StateSyncMessage : public ::omnetpp::cPacket
{
  protected:
    int droneId = 0;
    bool authenticated = false;
    omnetpp::opp_string commitment;
    long publicKey = 0;
    omnetpp::simtime_t lastAuthTime = SIMTIME_ZERO;
    int authCount = 0;
    bool fullSync = false;

  private:
    void copy(const StateSyncMessage& other);

  protected:
    bool operator==(const StateSyncMessage&) = delete;

  public:
    StateSyncMessage(const char *name=nullptr, short kind=0);
    StateSyncMessage(const StateSyncMessage& other);
    virtual ~StateSyncMessage();
    StateSyncMessage& operator=(const StateSyncMessage& other);
    virtual StateSyncMessage *dup() const override {return new StateSyncMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDroneId() const;
    virtual void setDroneId(int droneId);

    virtual bool getAuthenticated() const;
    virtual void setAuthenticated(bool authenticated);

    virtual const char * getCommitment() const;
    virtual void setCommitment(const char * commitment);

    virtual long getPublicKey() const;
    virtual void setPublicKey(long publicKey);

    virtual omnetpp::simtime_t getLastAuthTime() const;
    virtual void setLastAuthTime(omnetpp::simtime_t lastAuthTime);

    virtual int getAuthCount() const;
    virtual void setAuthCount(int authCount);

    virtual bool getFullSync() const;
    virtual void setFullSync(bool fullSync);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const StateSyncMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, StateSyncMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>DroneAuthMessages.msg:60</tt> by opp_msgtool.
 * <pre>
 * // GCS announces it's taking over
 * packet GCSAnnouncementMessage
 * {
 *     string newPrimaryAddress;       // "BackupGCS" or "PrimaryGCS"
 *     string reason;                  // "failover", "planned_switch", "recovery"
 *     simtime_t timestamp;            // Announcement time
 *     int droneCount;                 // How many drones should reconnect
 * }
 * </pre>
 */
class GCSAnnouncementMessage : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string newPrimaryAddress;
    omnetpp::opp_string reason;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    int droneCount = 0;

  private:
    void copy(const GCSAnnouncementMessage& other);

  protected:
    bool operator==(const GCSAnnouncementMessage&) = delete;

  public:
    GCSAnnouncementMessage(const char *name=nullptr, short kind=0);
    GCSAnnouncementMessage(const GCSAnnouncementMessage& other);
    virtual ~GCSAnnouncementMessage();
    GCSAnnouncementMessage& operator=(const GCSAnnouncementMessage& other);
    virtual GCSAnnouncementMessage *dup() const override {return new GCSAnnouncementMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getNewPrimaryAddress() const;
    virtual void setNewPrimaryAddress(const char * newPrimaryAddress);

    virtual const char * getReason() const;
    virtual void setReason(const char * reason);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);

    virtual int getDroneCount() const;
    virtual void setDroneCount(int droneCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GCSAnnouncementMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GCSAnnouncementMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>DroneAuthMessages.msg:68</tt> by opp_msgtool.
 * <pre>
 * // Drone acknowledges GCS switch
 * packet GCSSwitchAckMessage
 * {
 *     int droneId;                    // Which drone is acknowledging
 *     string newGCS;                  // Which GCS it switched to
 *     simtime_t switchTime;           // When switch completed
 *     bool successful;                // Switch successful?
 * }
 * </pre>
 */
class GCSSwitchAckMessage : public ::omnetpp::cPacket
{
  protected:
    int droneId = 0;
    omnetpp::opp_string newGCS;
    omnetpp::simtime_t switchTime = SIMTIME_ZERO;
    bool successful = false;

  private:
    void copy(const GCSSwitchAckMessage& other);

  protected:
    bool operator==(const GCSSwitchAckMessage&) = delete;

  public:
    GCSSwitchAckMessage(const char *name=nullptr, short kind=0);
    GCSSwitchAckMessage(const GCSSwitchAckMessage& other);
    virtual ~GCSSwitchAckMessage();
    GCSSwitchAckMessage& operator=(const GCSSwitchAckMessage& other);
    virtual GCSSwitchAckMessage *dup() const override {return new GCSSwitchAckMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDroneId() const;
    virtual void setDroneId(int droneId);

    virtual const char * getNewGCS() const;
    virtual void setNewGCS(const char * newGCS);

    virtual omnetpp::simtime_t getSwitchTime() const;
    virtual void setSwitchTime(omnetpp::simtime_t switchTime);

    virtual bool getSuccessful() const;
    virtual void setSuccessful(bool successful);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GCSSwitchAckMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GCSSwitchAckMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>DroneAuthMessages.msg:76</tt> by opp_msgtool.
 * <pre>
 * // Failover complete notification
 * packet FailoverCompleteMessage
 * {
 *     int dronesReconnected;          // How many drones reconnected
 *     simtime_t failoverStartTime;    // When failover started
 *     simtime_t failoverEndTime;      // When failover completed
 *     double failoverDuration;        // Duration in seconds
 * }
 * </pre>
 */
class FailoverCompleteMessage : public ::omnetpp::cPacket
{
  protected:
    int dronesReconnected = 0;
    omnetpp::simtime_t failoverStartTime = SIMTIME_ZERO;
    omnetpp::simtime_t failoverEndTime = SIMTIME_ZERO;
    double failoverDuration = 0;

  private:
    void copy(const FailoverCompleteMessage& other);

  protected:
    bool operator==(const FailoverCompleteMessage&) = delete;

  public:
    FailoverCompleteMessage(const char *name=nullptr, short kind=0);
    FailoverCompleteMessage(const FailoverCompleteMessage& other);
    virtual ~FailoverCompleteMessage();
    FailoverCompleteMessage& operator=(const FailoverCompleteMessage& other);
    virtual FailoverCompleteMessage *dup() const override {return new FailoverCompleteMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDronesReconnected() const;
    virtual void setDronesReconnected(int dronesReconnected);

    virtual omnetpp::simtime_t getFailoverStartTime() const;
    virtual void setFailoverStartTime(omnetpp::simtime_t failoverStartTime);

    virtual omnetpp::simtime_t getFailoverEndTime() const;
    virtual void setFailoverEndTime(omnetpp::simtime_t failoverEndTime);

    virtual double getFailoverDuration() const;
    virtual void setFailoverDuration(double failoverDuration);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FailoverCompleteMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FailoverCompleteMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline AuthCommit *fromAnyPtr(any_ptr ptr) { return check_and_cast<AuthCommit*>(ptr.get<cObject>()); }
template<> inline AuthChallenge *fromAnyPtr(any_ptr ptr) { return check_and_cast<AuthChallenge*>(ptr.get<cObject>()); }
template<> inline AuthResponse *fromAnyPtr(any_ptr ptr) { return check_and_cast<AuthResponse*>(ptr.get<cObject>()); }
template<> inline AuthResult *fromAnyPtr(any_ptr ptr) { return check_and_cast<AuthResult*>(ptr.get<cObject>()); }
template<> inline HeartbeatMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<HeartbeatMessage*>(ptr.get<cObject>()); }
template<> inline StateSyncMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<StateSyncMessage*>(ptr.get<cObject>()); }
template<> inline GCSAnnouncementMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<GCSAnnouncementMessage*>(ptr.get<cObject>()); }
template<> inline GCSSwitchAckMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<GCSSwitchAckMessage*>(ptr.get<cObject>()); }
template<> inline FailoverCompleteMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<FailoverCompleteMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DRONEAUTHMESSAGES_M_H

